{
    'name': 'Website Theme Framework',
    'description': 'Premium Website Theme Framework for ARMORAIT. Bootstrap 5, 40 snippets, customizer, SEO, animations.',
    'category': 'Theme/Corporate',
    'summary': '40 snippets, customizer, SEO, and Bootstrap 5 theme base',
    'sequence': 100,
    'version': '19.0.1.0.0',
    'depends': [
        'website',
    ],
    'data': [
        'data/generate_primary_template.xml',
        'data/ir_asset.xml',
        'data/theme_config.xml',
        'views/layouts/header_templates.xml',
        'views/layouts/footer_templates.xml',
        'views/layouts/mega_menu.xml',
        'views/layouts/breadcrumb.xml',
        'views/layouts/search.xml',
        'views/seo/website_seo.xml',
        'views/customizer/website_customizer.xml',
        'views/snippets/snippets_registry.xml',
        'views/snippets/s_tb_accordion.xml',
        'views/snippets/s_tb_animated_counter.xml',
        'views/snippets/s_tb_appointment_section.xml',
        'views/snippets/s_tb_before_after.xml',
        'views/snippets/s_tb_blog_cards.xml',
        'views/snippets/s_tb_call_to_action.xml',
        'views/snippets/s_tb_category_grid.xml',
        'views/snippets/s_tb_comparison_table.xml',
        'views/snippets/s_tb_contact_form.xml',
        'views/snippets/s_tb_countdown.xml',
        'views/snippets/s_tb_course_cards.xml',
        'views/snippets/s_tb_doctor_cards.xml',
        'views/snippets/s_tb_emergency_banner.xml',
        'views/snippets/s_tb_event_cards.xml',
        'views/snippets/s_tb_faq.xml',
        'views/snippets/s_tb_feature_cards.xml',
        'views/snippets/s_tb_floating_contact.xml',
        'views/snippets/s_tb_footer_variation.xml',
        'views/snippets/s_tb_gallery.xml',
        'views/snippets/s_tb_google_map.xml',
        'views/snippets/s_tb_header_variation.xml',
        'views/snippets/s_tb_hero_banner.xml',
        'views/snippets/s_tb_image_slider.xml',
        'views/snippets/s_tb_instagram_feed.xml',
        'views/snippets/s_tb_newsletter.xml',
        'views/snippets/s_tb_partners_logo.xml',
        'views/snippets/s_tb_portfolio_grid.xml',
        'views/snippets/s_tb_pricing_table.xml',
        'views/snippets/s_tb_process_steps.xml',
        'views/snippets/s_tb_product_showcase.xml',
        'views/snippets/s_tb_restaurant_menu.xml',
        'views/snippets/s_tb_services_grid.xml',
        'views/snippets/s_tb_statistics.xml',
        'views/snippets/s_tb_tabs.xml',
        'views/snippets/s_tb_teacher_cards.xml',
        'views/snippets/s_tb_team_members.xml',
        'views/snippets/s_tb_testimonials.xml',
        'views/snippets/s_tb_timeline.xml',
        'views/snippets/s_tb_video_banner.xml',
        'views/snippets/s_tb_whatsapp_button.xml',
    ],
                    'images': [
        'static/description/banner.png',
        'static/description/icon.png',
        'static/description/company_logo.png',
        'static/description/screenshot_theme_base_form.png',
        'static/description/screenshot_theme_base_list.png',
        'static/description/screenshot_theme_base_dashboard.png',
        'static/description/screenshot_theme_base_back.png',
    ],
    'author': 'ARMORA IT Technologies',
    'maintainer': 'ARMORA IT Technologies',
    'website': 'https://www.armorait.com',
    'license': 'OPL-1',
    'currency': 'USD',
    'price': 49.99,
    'live_test_url': 'https://www.armorait.com',
    'configurator_snippets': {
        'homepage': [
            's_tb_hero_banner',
            's_tb_services_grid',
            's_tb_feature_cards',
            's_tb_testimonials',
            's_tb_call_to_action',
        ],
    },
    'assets': {
        'web.assets_frontend': [
            'rn_theme_base/static/src/scss/theme.scss',
            'rn_theme_base/static/src/js/rn_theme_base.js',
            'rn_theme_base/static/src/js/mega_menu.js',
            'rn_theme_base/static/src/js/animations.js',
            'rn_theme_base/static/src/js/customizer.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
}
