# -*- coding: utf-8 -*-
{
    'name': 'Formula Fields',
    'summary': 'Create safe stored calculated fields without custom Python code',
    'description': 'Build stored formula fields for Odoo models with a safe AST expression engine.',
    'version': '19.0.1.0.0',
    'category': 'Productivity',
    'author': 'ARMORA IT Technologies',
    'maintainer': 'ARMORA IT Technologies',
    'website': 'https://www.armorait.com',
    'support': 'info@armorait.com',
    'license': 'OPL-1',
    'price': 9.99,
    'live_test_url': 'https://www.armorait.com',
    'currency': 'USD',
    'depends': ['base', 'mail', 'web', 'product', 'sale_management'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_config_parameter.xml',
        'data/formula_template_data.xml',
        'data/formula_field_data.xml',
        'views/formula_field_views.xml',
        'views/formula_template_views.xml',
        'views/product_template_views.xml',
        'views/settings_views.xml',
        'views/menu.xml',
        'wizard/formula_test_wizard_views.xml',
    ],
    'demo': [],
    'assets': {},
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': [
        'static/description/banner.png',
        'static/description/icon.png',
        'static/description/workflow.png',
        'static/description/dashboard.png',
        'static/description/designer.png',
    ],
}
