# -*- coding: utf-8 -*-
{
    'name': 'Resume AI Parser',
    'version': '19.0.1.0.0',
    'category': 'Human Resources/Recruitment',
    'summary': 'Parse CVs into skills, experience, and applicant records',
    'description': """
        Async resume parsing: PDF extraction, AI-structured JSON, skill normalization,
        experience calculation, and job match score. Uses queue_job when available.
    """,
    'depends': [
        'hr_recruitment',
        'hr_skills',
        'mail',
        'web',
        'base',
    ],
    # Use 'pdfminer' (import name) so dependency works even when 'packaging' is not installed
    'external_dependencies': {
        'python': ['pdfminer'],
    },
    'data': [
        'security/ir.model.access.csv',
        'data/resume_parser_cron.xml',
        'data/skill_normalization_data.xml',
        'views/hr_applicant_views.xml',
        'views/res_config_settings_views.xml',
        'wizard/hr_resume_bulk_upload_wizard_views.xml',
        'views/hr_resume_ai_parser_menus_views.xml',
    ],
    'author': 'ARMORA IT Technologies',
    'maintainer': 'ARMORA IT Technologies',
        'images': [
        'static/description/banner.png',
        'static/description/icon.png',
        'static/description/dashboard.png',
        'static/description/overview.png',
        'static/description/form.png',
        'static/description/list.png',
        'static/description/kanban.png',
        'static/description/wizard.png',
        'static/description/designer.png',
        'static/description/search.png',
        'static/description/settings.png',
        'static/description/report.png',
        'static/description/workflow.png',
        'static/description/mobile.png',
        'static/description/screenshot_real_copilot.png',
        'static/description/screenshot_real_crm.png',
    ],
    'installable': True,
    'application': False,
    'license': 'OPL-1',
    'currency': 'USD',
    'price': 79.99,
    'live_test_url': 'https://www.armorait.com',
}
