# -*- coding: utf-8 -*-
{
    'name': 'Filter Manager',
    'version': '19.0.1.0.0',
    'category': 'Productivity',
    'summary': 'Organize, share, pin, and manage Odoo filters with folders, favorites, recent history, and team sharing',
    'description': """
Filter Manager for Odoo 19 Community
====================================

Turn Odoo favorites into a first-class navigation tool with folders, pinning,
team sharing, usage analytics, and JSON import/export.
    """,
    'author': 'ARMORA IT Technologies',
    'maintainer': 'ARMORA IT Technologies',
    'website': 'https://www.armorait.com',
    'support': 'info@armorait.com',
    'license': 'OPL-1',
    'currency': 'USD',
    'price': 9.99,
    'live_test_url': 'https://www.armorait.com',
    'sequence': 53,
    'depends': ['base', 'mail', 'web', 'sale', 'account', 'crm', 'contacts', 'product'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_config_parameter.xml',
        'views/filter_folder_views.xml',
        'views/filter_views.xml',
        'views/filter_history_views.xml',
        'views/settings_views.xml',
        'wizard/filter_import_export_wizard_views.xml',
        'views/menu.xml',
    ],
    'demo': ['demo/demo.xml'],
        'images': [
        'static/description/banner.png',
        'static/description/icon.png',
        'static/description/dashboard.png',
        'static/description/overview.png',
        'static/description/form.png',
        'static/description/list.png',
        'static/description/kanban.png',
        'static/description/wizard.png',
        'static/description/designer.png',
        'static/description/search.png',
        'static/description/settings.png',
        'static/description/report.png',
        'static/description/workflow.png',
        'static/description/mobile.png',
        'static/description/hero.gif',
        'static/description/dashboard.gif',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
